spring:
  application:
    name: notificationservice
  config:
    import: optional:configserver:http://localhost:8071/

server:
  port: 9090

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
