spring:
  application:
    name: notificationservice
  config:
    import: optional:configserver:http://localhost:8071/

logging:
  level:
    org:
      apache:
        kafka:
          clients: error
          common: error
      spring:
        kafka: error
