eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/service-discovery/

spring:
  application:
    name: "notificationservice"
  config:
    import: "optional:configserver:http://localhost:8071/config-server"

